{{- if .Values.dindDaemonSet.enabled }}
{{ $name := include "fullname" . }}
apiVersion: {{ template "daemonset.apiVersion" . }}
kind: DaemonSet
metadata:
  name: {{ $name }}-dind
  labels:
    app: {{ $name }}-dind
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}-dind
  template:
    metadata:
      labels:
        app: {{ $name }}-dind
    spec:
      {{- if .Values.priorities.enabled }}
      priorityClassName: {{ $name }}-dind
      {{- end }}
      initContainers:
        - name: prep
          image: alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: docker-run
            mountPath: /var/buildkite/docker/run
          command:
            - /bin/sh
            - -c
            - rm -f /var/buildkite/docker/run/*.sock
      containers:
      - name: dind
        image: {{ .Values.dindDaemonSet.image }}
        args:
          - "--config-file"
          - "/etc/docker/docker-daemon.json"
          - "--data-root"
          - "/var/buildkite/docker/storage"
          - "--mtu"
          - "{{ .Values.dindDaemonSet.mtu | default "1450" }}"
{{ toYaml .Values.dindDaemonSet.args | indent 10 }}
        resources:
{{ toYaml .Values.dindDaemonSet.resources | indent 10 }}
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker/docker.sock
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-config
          mountPath: /etc/docker
        - name: docker-storage
          mountPath: /var/buildkite/docker
        - name: docker-run
          mountPath: /var/run/docker
        - name: buildkite-builds
          mountPath: /var/buildkite/builds
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - docker info > /dev/null
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - docker info > /dev/null
          initialDelaySeconds: 5
          periodSeconds: 10          
      volumes:
      - name: docker-config
        configMap:
          name: {{ $name }}-dind-dockerconfig
          defaultMode: 0644
      - name: docker-storage
        {{- if .Values.dindDaemonSet.storage.tmpfs }}
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.dindDaemonSet.storage.sizeLimit | default "16Gi" }}
        {{- else }}
        hostPath:
          path: /var/buildkite/docker
          type: DirectoryOrCreate
        {{- end }}
      - name: docker-run
        hostPath:
          path: /var/buildkite/docker/run
          type: DirectoryOrCreate
      - name: buildkite-builds
        hostPath:
          path: /var/buildkite/builds
          type: DirectoryOrCreate

{{- end }}